### ISSUE TITLE
Any way to provide app context to link resolver for nuxt-i18n compat?

### ISSUE THREAD

**Issue by zrisher** [nuxt-modules/prismic#107]
When writing the [`linkResolver`](https://prismic.io/docs/javascript/beyond-the-api/link-resolving) function, we must provide our full understanding of our app's routing. This works fine in simple cases.

However, some of us use [`nuxt-i18n`](https://i18n.nuxtjs.org/) to manage language-aware routing, which does some complicated things like discovering routes, merging them with custom language-specific paths, and siloing routes by language code. We can provide it with a full list of the languages we support, the default, etc.

It can be time-consuming and error prone to have to duplicate the final routing logic of `nuxt-i18n` when writing our `linkResolver` function. It would be significantly easier if we had access to `nuxt-i18n`'s helpers, which are provided to components via global mixins and as part of Nuxt's [`context.app`](https://nuxtjs.org/api/context/).

I believe this is the same issue that was mentioned here: https://github.com/nuxt-community/prismic-module/issues/23

I'm not super familiar with any of these libraries yet, so please forgive my lack of understanding here. Does anyone have suggestions on how to accomplish this? Perhaps we could amend how Prismic Nuxt loads the `linkResolver` before passing it to Prismic Vue - if it provided the plugin file with access to `context` and then expected it to return a constructed linkResolver function which makes use of the helpers it pulled from `context.app`?

**Comment by lihbr** [comment]
Hey @zrisher, I'm really sorry for the delay, might have slipped through my notifications 🙏

I understand the issue here and this is a great feedback! I definitely agree that it's not convenient, error-prone, to maintain a routing strategy for Prismic separated from the Nuxt i18n one and I'm afraid there's currently no way to overcome that.

As pointed out in https://github.com/nuxt-community/prismic-module/issues/23#issuecomment-487290764 you should have access to `doc.lang` in order to perform routing in your link resolver. An alternative method to resolving links if through the `apiOptions.routes` object, more info about it here: https://prismic.nuxtjs.org/configuration#new-routes-resolver

We are planning to work on a major version (v. 2) of this module in Q1 2021 next year and I'll definitely look for a way to grant access to Nuxt context inside the link resolver and HTML serializer :)

**Comment by lihbr** [comment]
I know this issue/feature request has been hanging in the balance for a while now and I'm sorry about that.

Nowadays, our preferred way of resolving documents URL at Prismic is now achieved through the Route Resolver: https://prismic.io/docs/route-resolver. It is not programmatic, it is just a rule object sent to the API so that document URLs don't need to be resolved at runtime anymore.
So I'm left a bit clueless as to how we could tighten integration with the i18n module here now 🤔

Thank you @zrisher for being a long-time contributor by the way, appreciate it ☺️

**Comment by zrisher** [comment]
Hi @lihbr, it is my pleasure to provide my feedback where I can on your excellent set of tools. Thanks for always being responsive.

It has been far too long since I looked at this particular use case to be able to say what this problem looks like now. Nuxt has changed quite a bit, and I don't have any current projects with it where I'm using an i18n module.

I think we can safely close this until someone else comes along with an understanding of something lacking in the current functionality.

Thank you!
